### ISSUE TITLE
Does the C# use any Window specific libs?

### ISSUE THREAD

**Issue by nstgc** [goosefraba19/StellarisUtils#1]
I saw this on Reddit and my eyes lit up. Then I saw .cs in the source code. Is there anything in there specific to Windows (meaning can I run this in Mono)?

**Comment by goosefraba19** [comment]
I've never used Mono, but I'm pretty sure there's nothing Windows specific. The C# application converts the savefiles to JSON, so it's only dependencies are Newtonsoft and some System libraries. Does the application have to be written for .Net Core to work in Mono?

That being said, if I can get a hold of a quicker parser in Python I'll phase out the C# code entirely.

**Comment by goosefraba19** [comment]
I converted the C# application to Python this morning and it runs fast enough for me, so I'm keeping it and removing the C# stuff.

**Comment by nstgc** [comment]
Thank!
